name: Update IPTV List

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-iptv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Show working directory and environment
      run: |
        pwd
        echo "Repository root contents:"
        ls -la
        echo "Current working directory structure:"
        find . -type f -name "*.m3u8" -o -name "*.py"
        
    - name: Run update script
      run: |
        # 确保我们在正确的目录
        cd $GITHUB_WORKSPACE
        python .github/workflows/update_iptv.py
      timeout-minutes: 5
        
    - name: Check file status
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Looking for m3u8 files:"
        find . -name "*.m3u8"
        echo "iptv2.m3u8 status:"
        ls -la iptv2.m3u8 || echo "File not found"
        if [ -f iptv2.m3u8 ]; then
          echo "File content preview:"
          head -n 5 iptv2.m3u8
          echo "File size:"
          stat iptv2.m3u8
          echo "File absolute path:"
          realpath iptv2.m3u8
        fi
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        echo "Git status before add:"
        git status
        git add iptv2.m3u8
        echo "Git status after add:"
        git status
        echo "Git diff staged:"
        git diff --staged
        if git diff --quiet && git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "自动更新IPTV列表 $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        fi
